services:
  ocelotapigateway:
    image: ffm-ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile

  accservice.api:
    image: ffm-accserviceapi
    build:
      context: .
      dockerfile: AccService.API/Dockerfile


  productcatalogservice.api:
    image: ffm-productcatalogserviceapi
    build:
      context: .
      dockerfile: ProductCatalogService.API/Dockerfile
  blogservice.api:
    image: ffm-blogserviceapi
    build:
      context: .
      dockerfile: BlogService.API/Dockerfile

  inventoryservice.api:
    image: ffm-inventoryserviceapi
    build:
      context: .
      dockerfile: InventoryService.API/Dockerfile

<<<<<<< HEAD
=======

>>>>>>> 5e297cb5cf5e183d600a4d1e61894fbe74e6a783
volumes:
   rabbitmq_data:


