services:
  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
    networks:
      - ffm-network
    restart: always
  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - ffm-network
    restart: always
  accservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    networks:
      - ffm-network
    restart: always
  productcatalogservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7000
    ports:
      - "7000:7000"
    networks:
      - ffm-network
    restart: always
  blogservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7200
    ports:
      - "7200:7200" 
    networks:
      - ffm-network
    restart: always
  inventoryservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7300
    ports:
      - "7300:7300"
    networks:
      - ffm-network
    restart: always

  voucherservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7400
    ports:
      - "7400:7400"
    networks:
      - ffm-network
    restart: always
 
networks:
  ffm-network:
     driver: bridge
     





