services:
  ocelotapigateway:
    image: ffm-ocelotapigateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile

  accservice.api:
    image: ffm-accserviceapi
    build:
      context: .
      dockerfile: AccService.API/Dockerfile


  productcatalogservice.api:
    image: ffm-productcatalogserviceapi
    build:
      context: .
      dockerfile: ProductCatalogService.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # App connect
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ffm-network
    restart: always
volumes:
   rabbitmq_data: